# Generated by Django 4.0.8 on 2022-11-20 18:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('vk', models.CharField(max_length=50, null=True, verbose_name='vk')),
                ('tg', models.CharField(max_length=50, null=True, verbose_name='tg')),
                ('fb', models.CharField(max_length=50, null=True, verbose_name='fb')),
                ('mail', models.CharField(max_length=50, null=True, verbose_name='mail')),
                ('inst', models.CharField(max_length=50, null=True, verbose_name='instagram')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакт',
            },
        ),
    ]
