# Generated by Django 4.0.8 on 2022-11-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='fb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fb'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='inst',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tg'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vk'),
        ),
    ]
