# Generated by Django 4.0.8 on 2022-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_contacts_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Фото'),
        ),
    ]
