# Generated by Django 4.0.8 on 2022-11-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_number_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Обложка'),
        ),
    ]
